### ISSUE TITLE
Deprecation Request: Remove non-important modules to focus resource on important-core modules

### ISSUE THREAD

**Issue by VictorTrustyDev** [EscanBE/evermint#41]
There are some modules from Evmos code base that kinda business-logic-specific and imo should be removed from Evermint codebase. Target:
- Make code base more light-weight
- Reduce distract for newbies, good for research, focus on the most core and important modules
- Reduce maintenance resource

Candidate modules:
- [x] [x/claims](https://docs.evmos.org/protocol/modules/claims) is the Air Drop module that business-specific. Completed by #73 
- [x] [x/inflation](https://docs.evmos.org/protocol/modules/inflation) is kinda business-specific also and let's use [Cosmos-SDK x/mint](https://docs.cosmos.network/main/build/modules/mint) instead. Completed by #54
- [x] [x/incentives](https://docs.evmos.org/protocol/modules/incentives) is kinda business-specific. Completed by #67 
- [x] [x/revenue](https://docs.evmos.org/protocol/modules/revenue) is kinda business-specific. Completed by #68
- [x] [x/recovery](https://docs.evmos.org/protocol/modules/recovery) aims to fix the address derivation issue. Completed by #69
- [x] [x/epochs](https://docs.evmos.org/protocol/modules/epochs) provided hooks for `x/inflation` and `x/incentives`. Completed by #70

___
Optional:
- [ ] [x/vesting](https://docs.evmos.org/protocol/modules/vesting) is kinda business-specific, shall we use [Cosmos-SDK x/auth/vesting](https://docs.cosmos.network/main/build/modules/auth/vesting) instead? How `EthAccount` compatible?
