### ISSUE TITLE
TODO: new features

### ISSUE THREAD

**Issue by VictorTrustyDev** [EscanBE/evermint#9]
- [x] `snapshot` command (completed by #12)
- [x] `inspect` command & sub commands (completed by #14)
  - [x] `inspect block`
  - [x] `inspect latest-block-number`
